version: 2
updates:
  - package-ecosystem: npm
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "frigg-fork"
    allow:
      - dependency-name: "@uniswap/token-lists"
      - dependency-name: "@uniswap/default-token-list"
